### ISSUE TITLE
FIRMS data looks broken

### ISSUE THREAD

**Issue by matemink** [leedrake5/Russia-Ukraine#15]
FIRMS table shows about 0 megabytes during the last month. Is this correct?

**Comment by leedrake5** [comment]
> FIRMS table shows about 0 megabytes during the last month. Is this correct?

Yes. There has been a large reduction in FIRMS data from the region in general - the Russian offensive has largely stalled and their disproportionately large artillery barrage was driving most of the observed variation. Since the Kharkiv Offensive that has been largely ceased.
