### ISSUE TITLE
Wrong deployed tanks in a proportional chart

### ISSUE THREAD

**Issue by Irrational-NX** [leedrake5/Russia-Ukraine#16]
In the "proportional tank losses" chart, isn't the top for the russian number of deployed tanks wrong?
It seems that the top is 1500, but it should be 2,840, according to the description beneath?

**Comment by leedrake5** [comment]
Not sure which you are referring too - though note that the number is adjusted for captures. 

There are two baselines - 2,840 deployed and a whopping 13K total in inventory (though many are useless). Both numbers are used in different plots and labeled accordingly.
