### ISSUE TITLE
Please add a table, which sums up all losses per system

### ISSUE THREAD

**Issue by christianfinckler1212** [leedrake5/Russia-Ukraine#17]
It would be very interesting to see the summed losses per system.
For example, which tank models were used and lost.
In a chart visualisation it would also be interesting, when which system started to get losses, sxplaining when which system got introduced into this war.

You could then see, if russia is slowly using more and more old equipment.

Thank you

**Comment by leedrake5** [comment]
It is available in the shiny app. To run locally:

`shiny::runGitHub("leedrake5/Russia-Ukraine", subdir="shinyApp")
`
You can access a server deployed version here: https://bleedrake.shinyapps.io/Russia-Ukraine/
