### ISSUE TITLE
Time scale

### ISSUE THREAD

**Issue by norpadon** [leedrake5/Russia-Ukraine#24]
Could you please add better markings on the time axis? Ideally month+year. Otherwise it is very hard to read the charts.

Also having separate plots just for the last month would be helpful to understand recent trends.

**Comment by leedrake5** [comment]
I definitely need to add year, will do that this week. 

I separated each part of the war into its own section with previous losses zeroed out. You can find the current offensive here: https://github.com/leedrake5/Russia-Ukraine/blob/main/5_summer_2023_offensive.md.

Links to the others are on the main page. Also currently working on Naalsio's Zaporizhizhia geolocation losses for Orkhiv and Starymaiorske.

**Comment by leedrake5** [comment]
Update is finished, years should be included across the board.
