### ISSUE TITLE
Data is missing since 23-12-24.

### ISSUE THREAD

**Issue by valerinaryshkin** [leedrake5/Russia-Ukraine#29]
Looks like scraper does not scrape Russian losses correctly since 2023-12-24
Is it possible to fix this?

Data is missing since 23-12-24
https://github.com/leedrake5/Russia-Ukraine/tree/main/data/bySystem/Totals/Full/2023-12-24.csv
https://github.com/leedrake5/Russia-Ukraine/tree/main/data/bySystem/Totals/Full/2023-12-25.csv
https://github.com/leedrake5/Russia-Ukraine/tree/main/data/bySystem/Totals/Full/2023-12-26.csv
https://github.com/leedrake5/Russia-Ukraine/tree/main/data/bySystem/Totals/Full/2023-12-27.csv

**Comment by leedrake5** [comment]
Sorry I missed this early, I ran into this and fixed a month ago. I clicked on the links and they are now working, let me know if I should reopen.
