### ISSUE TITLE
How has Ukrainian equipment been resurrected(undestroyed)?

### ISSUE THREAD

**Issue by mansillo** [leedrake5/Russia-Ukraine#3]
[How has Ukrainian equipment been resurrected(undestroyed)?](https://raw.githubusercontent.com/leedrake5/Russia-Ukraine/master/Plots/current_destroyed.jpg?)

**Comment by leedrake5** [comment]
I am unclear on what is being asked, could you please clarify?

**Comment by mansillo** [comment]
It's no longer problematic.  When I posted it the Ukrainian data was a negative integer than a positive. If it were negative it would mean the equipment would be "undestroyed" which seems ridiculous - perhaps repaired or additional equipment received. Now the plot is sensible so, not an issue any issue.

**Comment by leedrake5** [comment]
Will close this - thank you for the clarification. Because I draw from a public google sheet, there is a possibility of an error, though these are hopefully stamped out within a few hours of being identified.
