### ISSUE TITLE
Raw Daily since 2023-12-24.csv country is always Ukraine

### ISSUE THREAD

**Issue by makson96** [leedrake5/Russia-Ukraine#30]
Since:
https://github.com/leedrake5/Russia-Ukraine/blob/main/data/bySystem/Raw/Daily/2023-12-24.csv
to this date column country seems to be always Ukraine, despite clearly addressing Russian losses:
![github_ukraine](https://github.com/leedrake5/Russia-Ukraine/assets/1833284/9f7846ab-c63d-4e76-abfb-66d151d6fb5f)

**Comment by bl81hi** [comment]
Some systems are still marked as Russian, e.g. 78 T-62M, but most systems are Ukraine.

**Comment by makson96** [comment]
Issue seems to be fixed now.

**Comment by leedrake5** [comment]
Hi all, 

Closing, but if you find there are still errors please let me know and I will get them fixed. This repo can be sensitive to various changes made by Oryx, so good to get them all addressed.
